version: '3.9'

services:
  django:
    build: .
    command: bash -c "python manage.py migrate account admin auth contenttypes sessions socialaccount && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env  # Load environment variables from .env

